#!/bin/sh

sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_WT_HBO1_rep1_R1.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_WT_HBO1_rep1_R2.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_WT_Men1_rep1_R1.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_WT_Men1_rep1_R2.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_WT_H3K27me3_rep1_R1.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_WT_H3K27me3_rep1_R2.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_WT_H3K4me3_rep1_R1.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_WT_H3K4me3_rep1_R2.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_WT_IgG_rep1_R1.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_WT_IgG_rep1_R2.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_HBO1KO_HBO1_rep1_R1.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_HBO1KO_HBO1_rep1_R2.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_HBO1KO_Men1_rep1_R1.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_HBO1KO_Men1_rep1_R2.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_HBO1KO_H3K27me3_rep1_R1.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_HBO1KO_H3K27me3_rep1_R2.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_HBO1KO_H3K4me3_rep1_R1.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_HBO1KO_H3K4me3_rep1_R2.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_HBO1KO_IgG_rep1_R1.sh
sbatch scripts/CnR_HBO1_pipeline/01_fastqc_beforetrim/batch_sh/fastqc_beforetrim_HeLa_HBO1KO_IgG_rep1_R2.sh