#!/bin/sh

sbatch scripts/CnR_HBO1_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_WT_HBO1_rep1.sh
sbatch scripts/CnR_HBO1_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_WT_Men1_rep1.sh
sbatch scripts/CnR_HBO1_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_WT_H3K27me3_rep1.sh
sbatch scripts/CnR_HBO1_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_WT_H3K4me3_rep1.sh
sbatch scripts/CnR_HBO1_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_WT_IgG_rep1.sh
sbatch scripts/CnR_HBO1_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_HBO1KO_HBO1_rep1.sh
sbatch scripts/CnR_HBO1_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_HBO1KO_Men1_rep1.sh
sbatch scripts/CnR_HBO1_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_HBO1KO_H3K27me3_rep1.sh
sbatch scripts/CnR_HBO1_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_HBO1KO_H3K4me3_rep1.sh
sbatch scripts/CnR_HBO1_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_HBO1KO_IgG_rep1.sh